const path = require('path');
const fs = require('fs');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: [
        'eventsource-polyfill',
        'babel-polyfill',
        './src/app.js'
    ],
    output: {
        filename: 'bundle.js',
        path: './dist',
        publicPath: '/',
        pathinfo: true
    },
    resolve: {
        extensions: ['', '.js', '.jsx']
    },
    devtool: 'cheap-module-eval-source-map',
    module: {
        preLoaders: [
            {
                test: /\.jsx?$/,
                exclude: '/node_modules/',
                loader: 'eslint'
            }
        ],
        loaders: [
            {
                test: /\.js$/,
                loader: ['babel'],
                exclude: /node_modules/,
                query: {
                    presets: ['react-hmre']
                }
            }
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
        new webpack.NoErrorsPlugin(),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify('development')
        }),
        new HtmlWebpackPlugin({
            inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
            templateContent: fs.readFileSync(
                path.resolve(process.cwd(), 'src/index.html')
            ).toString()
        })
    ]
};
